#####################################
#                                   #
#  @author      : 00xWolf           #
#    GitHub    : @mmsaeed509       #
#    Developer : Mahmoud Mohamed   #
#  﫥  Copyright : Mahmoud Mohamed   #
#                                   #
#####################################

# Use an official Python runtime as a parent image #
FROM python

# Set the working directory in the container #
WORKDIR /app

# Copy the current directory contents into the container at /app #
COPY . /app

# Run app.py when the container launches #
CMD ["python", "rng.py"]
